
spring:
  datasource:
    url: jdbc:h2:mem:forumTest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    "[org.springframework.web]": ERROR
    "[org.martikan.forum-api]": DEBUG
    "[org.hibernate]": DEBUG