server:
  port: ${PORT:0}

spring:
  application:
    name: forum-api
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
  liquibase:
    enabled: true
    url: ${DATASOURCE_URL}
    user: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    change-log: classpath:/db/changelog/changelog-master.xml

management:
  endpoint:
    shutdown:
      enabled: true