server:
  port: ${PORT:8085}

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:forumTest}
    username: ${DATASOURCE_USER:sa}
    password: ${DATASOURCE_PASSWORD:}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  liquibase:
    enabled: true
    url: ${DATASOURCE_URL:jdbc:h2:mem:forumTest}
    user: ${DATASOURCE_USER:sa}
    password: ${DATASOURCE_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include: '*'

# token:
#   expiration: ${TOKEN_EXPIRATION:864000000} # 10 days by default
#   secret: ${TOKEN_SECRET:asdWasdWASGHEt31Sh34As5}

logging:
  level:
    "[org.springframework.web]": ERROR
    "[org.martikan.forum-api]": DEBUG
    "[org.hibernate]": DEBUG